version: "3.8"

volumes:
  postgres_data_typeorm:
    driver: local
  postgres_data_prisma:
    driver: local
  postgres_data_generic:
    driver: local

services:
  db-1:
    container_name: postgres-db-typeorm
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data_typeorm:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: typeorm
      POSTGRES_USER: typeorm
      POSTGRES_PASSWORD: typeorm
    ports:
      - 5435:5432
  db-2:
    container_name: postgres-db-prisma
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data_prisma:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: prisma
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    ports:
      - 5436:5432
  db-3:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data_generic:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5437:5432
